name: FateAvatar
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - pillow=9.4.0
  - pip=24.0
  - pthread-stubs=0.4
  - pysocks=1.7.1
  - python=3.8.19
  - python_abi=3.8
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - requests=2.32.1
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tbb=2021.12.0
  - tk=8.6.13
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - basicsr==1.4.2
      - cachetools==5.3.3
      - chumpy==0.70
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==3.0.10
      - dearpygui==1.11.1
      - facexlib==0.3.0
      - filterpy==1.4.5
      - fonttools==4.51.0
      - future==1.0.0
      - gfpgan==1.3.8
      - grpcio==1.64.0
      - imageio==2.22.0
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - llvmlite==0.41.1
      - lmdb==1.4.1
      - lpips==0.1.4
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - networkx==3.1
      - ninja==1.11.1.1
      - numba==0.58.1
      - numpy==1.23.0
      - oauthlib==3.2.2
      - opencv-python==4.9.0.80
      - packaging==24.0
      - platformdirs==4.2.2
      - plyfile==1.0.3
      - portalocker==2.8.2
      - protobuf==5.26.1
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pygments==2.18.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - realesrgan==0.3.0
      - requests-oauthlib==2.0.0
      - rich==13.7.1
      - rsa==4.9
      - scikit-image==0.19.3
      - scipy==1.10.1
      - six==1.16.0
      - tabulate==0.9.0
      - tb-nightly==2.14.0a20230808
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - tifffile==2023.7.10
      - tomli==2.0.1
      - tqdm==4.66.4
      - werkzeug==3.0.3
      - yacs==0.1.8
      - yapf==0.40.2
      - zipp==3.18.2