dataset:
  use_mean_expression: True
  use_var_expression: True
  canonical_pose: 0.2
  use_background: False
  load_images: True
  img_res: [512, 512]
  train:
    subsample: 1
  test:
    subsample: 1

loss:
  GT_lbs_milestones:  [20, 30, 50, 70]
  GT_lbs_factor:  0.5
  weight:
    rgb_loss:   1.0
    vgg_loss:   0.0 # it will cause training failure in black background settings
    dssim_loss: 0.25
    lbs_loss:   10.0

model:
  prune_thresh: 0.1

  geometry_network:
    d_in: 3
    d_out:  1
    feature_vector_size: 3
    dims: [256, 256, 256, 256, 256, 256, 256]
    geometric_init: True
    bias: 0.6
    skip_in:  [3]
    weight_norm:  True
    multires: 6

  rendering_network:
    d_in: 3
    d_out:  3
    feature_vector_size:  0
    dims: [64, 64]
    weight_norm:  True
    multires_view:  0
    multires_pnts:  0

  gaussian_network:
    d_in: 3
    d_out:  8
    feature_vector_size:  0
    dims: [64, 64]
    weight_norm:  True
    multires_view:  0
    multires_pnts:  0

  deformer_network:
    d_in: 3
    dims: [128, 128, 128, 128]
    weight_norm:  True
    multires: 0
    ghostbone:  True
    deform_c: True

  point_cloud:
    n_init_points:  400
    max_points: 100000


training:
  lr: 0.0001
  upsample_freq: 5
  # optimize flame coefficients in imavatar dataset
  tracking_lr: 0.0005
  epochs:
    imavatar: 100
    insta: 100
    4dface: 100
    finetune: 50  # for imavatar dataset

